# Generated by Django 5.1.4 on 2024-12-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Title', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Booktype', models.CharField(max_length=30)),
                ('Chapters', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=50)),
                ('Tag', models.CharField(max_length=100)),
            ],
        ),
    ]
